### ISSUE TITLE
 error: ‘False’ was not declared in this scope

### ISSUE THREAD

**Issue by picca** [tango-controls/pytango#291]
Hello, I know that this is quite old, but I would like to share this error during a build on Debian unstable.

Cheers

Fred

```
In file included from /usr/include/c++/8/cassert:44,
                 from /builds/science-team/pytango/debian/output/pytango-9.2.5/ext/tgutils.h:14,
                 from /builds/science-team/pytango/debian/output/pytango-9.2.5/ext/from_py.h:22,
                 from /builds/science-team/pytango/debian/output/pytango-9.2.5/ext/pytgutils.h:19,
                 from /builds/science-team/pytango/debian/output/pytango-9.2.5/ext/device_data.cpp:13:
/builds/science-team/pytango/debian/output/pytango-9.2.5/ext/device_data.cpp: In function ‘boost::python::api::object PyDeviceData::extract_array(Tango::DeviceData&, boost::python::api::object&, PyTango::ExtractAs) [with long int tangoArrayTypeConst = 31]’:
/builds/science-team/pytango/debian/output/pytango-9.2.5/ext/device_data.cpp:185:20: error: ‘False’ was not declared in this scope
             assert(False);
                    ^~~~~
/builds/science-team/pytango/debian/output/pytango-9.2.5/ext/device_data.cpp:185:20: note: suggested alternative: ‘raise’
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
E: pybuild pybuild:341: build: plugin distutils failed with: exit code=1: /usr/bin/python setup.py build 
dh_auto_build: pybuild --build -i python{version} -p 2.7 returned exit code 13
````

**Comment by ajoubertza** [comment]
@picca This has been fixed.  Available since v9.3.0.
See PR #262.

Can I close this issue?

**Comment by picca** [comment]
Yes, I was just asking because I just trig one of my CI pipeline.

I am waiting for tango 9.3.X before requesting an upload of pytango 9.3.3


Cheers

Fred

**Comment by andygotz** [comment]
I know @bourtemb is working on completing the 9.3.x release. He is close to completion. 

We had a question for @picca : when would the new release of pytango 9.3.3 be included in the debian packaging e.g. would it be available for Debian 10 as a replacement for 9.2.5?

**Comment by picca** [comment]
> We had a question for @picca<https://github.com/picca> : when would the new release of pytango 9.3.3 be included in the debian packaging e.g. would it be available > for Debian 10 as a replacement for 9.2.5?

Yes it possible, we call this a backport.
So once we have a tango 9.3.3 in testing, it will be possible to prepare a backport for Debian 10 which is already released ;).
I think that pytango should be also backported in order to have a coherent stack.
We also need to check that taurus from buster is compatible with pytango 9.3.3.

So, I would say, it is important to prepare a fully working stack in Debian testing, and then backports all the stack at once.

Juste to avoid bad user experience.

I personnaly do not have time to test all this, but I can help review and upload the packages, once they are in salsa.debian.org

We need also to considere the Ubuntu deadlines in order to avoid a brekage in the next Ubuntu release.

Cheers

Fred

**Comment by ajoubertza** [comment]
OK.  Closing this.
(Note: next pytango release will be 9.3.1).
