### ISSUE TITLE
AttributeError: 'DeviceAttribute' object has no attribute 'value' for zero length arrays

### ISSUE THREAD

**Issue by cmft** [tango-controls/pytango#271]
With PyTango 9.3.0 some `deviceattribute` do not have `value` and `w_value` attributes.
this does not happened at least in v9.2.0.

You can reproduce the error:
```
import tango
dev_name = 'sys/tg_test/1'
dev = tango.DeviceProxy(dev_name)

for attr_name in ['short_spectrum', 'short_image', 'boolean_image', 'boolean_spectrum']:
    attr = dev.read_attribute(attr_name)
    print(attr.value)
```
With PyTango 9.2.0 you got `None`

**Comment by sergirubio** [comment]
For me it is a bug; even if attributes have no value, the returned struct should be consistent

**Comment by ajoubertza** [comment]
@cmft I cannot reproduce this.  I tried with PyTango 9.3.0 on libtango 9.2.5 (under Python 2.7), and again with libtango 9.3.2alpha1 (under Python 3.6.8).  In this case I was testing on a Docker container, based on Ubuntu Trusty.

```
$ ipython
Python 2.7.6 (default, Nov 13 2018, 12:45:42) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tango

In [2]: tango.__version__
Out[2]: '9.3.0'

In [3]: tango._tango.__tangolib_version__
Out[3]: '9.2.5'

In [4]: dev_name = 'sys/tg_test/1'

In [5]: dev = tango.DeviceProxy(dev_name)

In [6]: for attr_name in ['short_spectrum', 'short_image', 'boolean_image', 'boolean_spectrum']:
   ...:     attr = dev.read_attribute(attr_name)
   ...:     print(attr.value)
   ...:     
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]
```

PyTango recompiled from source inside a conda environment, similar to the PyTango unit tests:
```
$ ipython3 
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tango                                                                                                                               

In [2]: tango.__version__                                                                                                                          
Out[2]: '9.3.0'

In [3]: tango._tango.__tangolib_version__                                                                                                          
Out[3]: '9.3.2'

In [4]: dev_name = 'sys/tg_test/1'                                                                                                                 

In [5]: dev = tango.DeviceProxy(dev_name)                                                                                                          

In [6]: for attr_name in ['short_spectrum', 'short_image', 'boolean_image', 'boolean_spectrum']: 
   ...:     attr = dev.read_attribute(attr_name) 
   ...:     print(attr.value) 
   ...:                                                                                                                                            
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]

In [7]: for attr_name in ['short_spectrum', 'short_image', 'boolean_image', 'boolean_spectrum']: 
   ...:     attr = dev.read_attribute(attr_name) 
   ...:     print(attr.w_value) 
   ...:                                                                                                                                            
[0]
[]
[]
[ True]
```

**Comment by cmft** [comment]
Hi @AntoineDupre ,
It happens with any attribute that has not been initialized any time.
The expected values (base on Tango 9.2.5, PyTango 9.2.0 test and python2.7):
```
In [1]: import tango
   ...: dev_name = 'sys/tg_test/1'
   ...: dev = tango.DeviceProxy(dev_name)
   ...: 
   ...: for attr_name in ['short_spectrum', 'short_image', 'boolean_image', 'boolean_spectrum']:
   ...:     attr = dev.read_attribute(attr_name)
   ...:     print(attr.value)
   ...:     
None
None
None
None
```
Reading from Jive you should get:
```
Attribute: sys/tg_test/1/short_spectrum
Duration: 1 msec
measure date: 09/04/2019 10:52:52 + 405ms
quality: VALID
dim x: 0
Array cannot be displayed. (You may change the AnswerLimitMin)
Array cannot be displayed. (You may change the AnswerLimitMin)
```
If you had initialized the attribute, the only way to reproduce the error is setting its dim to `0` e.g.  for  sys/tg_test/1/short_spectrum write value `[]`  from jive (I do not why).

With Tango 9.3.3 and PyTango 9.3.0 (I can share you the .deb packages) I got the reported exception.
Is public your docker image? If yes, could you share the link and  I will try to reproduce the error there.

**Comment by cmft** [comment]
I got the same error using the tango python3 version

**Comment by ajoubertza** [comment]
@cmft OK, I see.  So the problem is for spectrum and image type attributes that have a dimension of zero.

Sorry, my docker image isn't public, but I can reproduce that result if I first write an empty array to the attribute.  Interestingly, if I combine PyTango 9.3.0 code with Tango 9.2.5, it works ok - this suggests a change in libtango is causing this.  See example below:

Failure:
```
(buildenv) tango-cs@a8e2c2cda025:~/build$ ipython
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tango                                                                                                                               

In [2]: tango.__version__                                                                                                                          
Out[2]: '9.3.0'

In [3]: tango._tango.__tangolib_version__                                                                                                          
Out[3]: '9.3.2'

In [4]: dev = tango.DeviceProxy('sys/tg_test/1')                                                                                                   

In [5]: dev.write_attribute('short_spectrum', [])                                                                                                  

In [6]: attr = dev.read_attribute('short_spectrum')                                                                                                

In [7]: print(attr.value)                                                                                                                          
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-1e747363aef4> in <module>
----> 1 print(attr.value)

AttributeError: 'DeviceAttribute' object has no attribute 'value'

In [8]: attr                                                                                                                                       
Out[8]: DeviceAttribute(data_format = tango._tango.AttrDataFormat.SPECTRUM,
dim_x = 0, dim_y = 0, has_failed = False, is_empty = False, name = 'short_spectrum',
nb_read = 0, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID,
r_dimension = AttributeDimension(dim_x = 0, dim_y = 0),
time = TimeVal(tv_nsec = 0, tv_sec = 1554841301, tv_usec = 570519),
type = tango._tango.CmdArgType(100),
w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0))
```

Working using libtango 9.2.5 (and Python 2.7 compared to 3.6.8 above, but I don't think that is the cause) :
```
tango-cs@a8e2c2cda025:~$ ipython
Python 2.7.6 (default, Nov 13 2018, 12:45:42) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tango

In [2]: tango.__version__
Out[2]: '9.3.0'

In [3]: tango._tango.__tangolib_version__
Out[3]: '9.2.5'

In [4]: dev = tango.DeviceProxy('sys/tg_test/1')

In [5]: dev.write_attribute('short_spectrum', [])

In [6]: attr = dev.read_attribute('short_spectrum')

In [7]: print(attr.value)
None

In [8]: attr
Out[8]: DeviceAttribute(data_format = tango._tango.AttrDataFormat.SPECTRUM,
dim_x = 0, dim_y = 0, has_failed = False, is_empty = True, name = 'short_spectrum',
nb_read = 0, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID,
r_dimension = AttributeDimension(dim_x = 0, dim_y = 0),
time = TimeVal(tv_nsec = 0, tv_sec = 1554841244, tv_usec = 149589),
type = tango._tango.CmdArgType(4294967295),
value = None,
w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0),
w_value = None)
```

Besides the missing `value` and `w_value` fields, the only other difference I notice in the returned attributes is the working one has
`type = tango._tango.CmdArgType(4294967295)`, while the failure has
`type = tango._tango.CmdArgType(100)`

The default length to the `short_spectrum` attribute is 256 bytes, not 100, so not sure where that comes from.  It is possible this difference isn't relevant to the problem.

Maybe @bourtemb or another cppTango person can comment if something like this has changed?

**Comment by cmft** [comment]
Hi @ajoubertza ,
I saw the problem also testing sardana with not spectrum values. It is more difficult to testing for you; since you need to create a Pool and MS; and provisioning elements e.g. running sar_demo macro from spock; but you will see the problem

**Comment by cmft** [comment]
> I saw the problem also testing sardana with not spectrum values. It is more difficult to testing for you; since you need to create a Pool and MS; and provisioning elements e.g. running sar_demo macro from spock; but you will see the problem

Sorry to introduce noise, the affected attributes are arrays

**Comment by jairomoldes** [comment]
A change introduce in cpp tango 9.3.3 is causing pytango to fail to detecting that the attribute is empty.
The DeviceAttribute.is_empty() function has been changed and now it returns a different value. This was introduced in cpp tango:
https://github.com/tango-controls/cppTango/pull/393

This pull request solves the problem:
https://github.com/tango-controls/pytango/pull/273

**Comment by adityadangeska** [comment]
Hello, I am facing the same error on Python 3.6.8. The attribute is string array.
Here is my tango version:
>>> tango.__version__
9.3.2
>>> tango._tango.__tangolib_version__
'9.3.3'
How this can be resolved?

**Comment by ajoubertza** [comment]
@adityadangeska I assume you are referring to [this](https://gitlab.com/ska-telescope/lmc-base-classes/blob/17879d581f6c66cbc26df8d7dd604979302d275b/skabase/SKASubarray/test/SKASubarray_test.py#L360).  Using the version you've indicated above (PyTango 9.3.1 - there is no v9.3.2 of PyTango yet), the attribute I read back, using `tango_context.device.read_attribute('configuredCapabilities')`, does include a `value` field set to `None`, as expected:

```
attr: DeviceAttribute(data_format = tango._tango.AttrDataFormat.SPECTRUM, dim_x = 0, dim_y = 0,
has_failed = False, is_empty = True, name = 'configuredCapabilities', nb_read = 0, nb_written = 0,
quality = tango._tango.AttrQuality.ATTR_VALID,
r_dimension = AttributeDimension(dim_x = 0, dim_y = 0),
time = TimeVal(tv_nsec = 0, tv_sec = 1574233037, tv_usec = 76320),
type = tango._tango.CmdArgType(100),
value = None,
w_dim_x = 0, w_dim_y = 0,
w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None) 
``` 

Using the high level API to read the attribute, returns `None`, as expected, when the list is empty.

```
In [1]: import tango                                                                                                                        

In [2]: print(tango.utils.info())                                                                                                           
PyTango 9.3.1 (9, 3, 1)
PyTango compiled with:
    Python : 3.7.3
    Numpy  : 1.17.2
    Tango  : 9.3.3
    Boost  : 1.67.0

PyTango runtime is:
    Python : 3.7.3
    Numpy  : 1.17.2
    Tango  : 9.3.3
    Boost  : 0.0.0
```
